;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


music_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Dungeon

@instruments:
	.word @env1,@env0,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ce,$cf,$00,$01


; Dungeon
@song0ch0:
	.byte $fb,$01
@song0ch0loop:
@ref0:
	.byte $80,$0e,$cd,$0d,$a5,$00,$f9,$cb
@ref1:
	.byte $07,$cd,$06,$a5,$00,$f9,$cb
	.byte $fd
	.word @song0ch0loop

; Dungeon
@song0ch1:
@song0ch1loop:
@ref2:
	.byte $f9,$f9,$cb
@ref3:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song0ch1loop

; Dungeon
@song0ch2:
@song0ch2loop:
@ref4:
	.byte $f9,$f9,$cb
@ref5:
	.byte $cf,$80,$1e,$a5,$00,$f9,$cb
	.byte $fd
	.word @song0ch2loop

; Dungeon
@song0ch3:
@song0ch3loop:
@ref6:
	.byte $f9,$f9,$cb
@ref7:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song0ch3loop

; Dungeon
@song0ch4:
@song0ch4loop:
@ref8:
	.byte $f9,$f9,$cb
@ref9:
	.byte $f9,$f9,$cb
	.byte $fd
	.word @song0ch4loop
